version: '3.8'

services:
  web:
    build: .
    container_name: crm_lead_web
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    networks:
      - pyq_mysql_prod_default
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    mem_limit: 512m
    memswap_limit: 512m
    cpus: "1.0"

networks:
  pyq_mysql_prod_default:
    external: true
